/*
  Warnings:

  - You are about to drop the `interests` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `matches` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `socials` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `user` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `userInterest` table. If the table is not empty, all the data it contains will be lost.

*/
-- CreateEnum
CREATE TYPE "MatchStatus" AS ENUM ('MATCHED', 'REQUESTED', 'SUCCESS', 'REJECTED');

-- DropForeignKey
ALTER TABLE "matches" DROP CONSTRAINT "matches_useroneId_fkey";

-- DropForeignKey
ALTER TABLE "matches" DROP CONSTRAINT "matches_usertwoId_fkey";

-- DropForeignKey
ALTER TABLE "socials" DROP CONSTRAINT "socials_userId_fkey";

-- DropForeignKey
ALTER TABLE "userInterest" DROP CONSTRAINT "userInterest_interestID_fkey";

-- DropForeignKey
ALTER TABLE "userInterest" DROP CONSTRAINT "userInterest_userId_fkey";

-- DropTable
DROP TABLE "interests";

-- DropTable
DROP TABLE "matches";

-- DropTable
DROP TABLE "socials";

-- DropTable
DROP TABLE "user";

-- DropTable
DROP TABLE "userInterest";

-- DropEnum
DROP TYPE "match_status";

-- CreateTable
CREATE TABLE "User" (
    "userId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" STRING NOT NULL,
    "username" STRING NOT NULL,
    "email" STRING NOT NULL,
    "bio" STRING,

    CONSTRAINT "User_pkey" PRIMARY KEY ("userId")
);

-- CreateTable
CREATE TABLE "Interests" (
    "interestId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "interestName" STRING NOT NULL,

    CONSTRAINT "Interests_pkey" PRIMARY KEY ("interestId")
);

-- CreateTable
CREATE TABLE "Socials" (
    "userId" STRING NOT NULL,
    "linkedin" STRING,
    "github" STRING,
    "twitter" STRING,
    "kaggle" STRING,

    CONSTRAINT "Socials_pkey" PRIMARY KEY ("userId")
);

-- CreateTable
CREATE TABLE "Matches" (
    "matchId" STRING NOT NULL,
    "matched_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "useroneId" STRING NOT NULL,
    "usertwoId" STRING NOT NULL,
    "statone" BOOL NOT NULL,
    "stattwo" BOOL NOT NULL,
    "mfactor" FLOAT8 NOT NULL,
    "mstatus" "MatchStatus" NOT NULL,

    CONSTRAINT "Matches_pkey" PRIMARY KEY ("matchId")
);

-- CreateTable
CREATE TABLE "_UserInterests" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "User_userId_username_email_idx" ON "User"("userId", "username", "email");

-- CreateIndex
CREATE UNIQUE INDEX "Interests_interestName_key" ON "Interests"("interestName");

-- CreateIndex
CREATE INDEX "Interests_interestId_interestName_idx" ON "Interests"("interestId", "interestName");

-- CreateIndex
CREATE UNIQUE INDEX "Socials_userId_key" ON "Socials"("userId");

-- CreateIndex
CREATE INDEX "Socials_userId_idx" ON "Socials"("userId");

-- CreateIndex
CREATE INDEX "Matches_useroneId_usertwoId_mstatus_matchId_idx" ON "Matches"("useroneId", "usertwoId", "mstatus", "matchId");

-- CreateIndex
CREATE UNIQUE INDEX "Matches_useroneId_usertwoId_key" ON "Matches"("useroneId", "usertwoId");

-- CreateIndex
CREATE UNIQUE INDEX "_UserInterests_AB_unique" ON "_UserInterests"("A", "B");

-- CreateIndex
CREATE INDEX "_UserInterests_B_index" ON "_UserInterests"("B");

-- AddForeignKey
ALTER TABLE "Socials" ADD CONSTRAINT "Socials_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("userId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Matches" ADD CONSTRAINT "Matches_useroneId_fkey" FOREIGN KEY ("useroneId") REFERENCES "User"("userId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Matches" ADD CONSTRAINT "Matches_usertwoId_fkey" FOREIGN KEY ("usertwoId") REFERENCES "User"("userId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_UserInterests" ADD CONSTRAINT "_UserInterests_A_fkey" FOREIGN KEY ("A") REFERENCES "Interests"("interestId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_UserInterests" ADD CONSTRAINT "_UserInterests_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("userId") ON DELETE CASCADE ON UPDATE CASCADE;
